//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui_Travel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M120Entities : DbContext
    {
        public M120Entities()
            : base("name=M120Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelBild> HotelBilds { get; set; }
        public virtual DbSet<Kunde> Kundes { get; set; }
        public virtual DbSet<Kunde_Reise> Kunde_Reise { get; set; }
        public virtual DbSet<Land> Lands { get; set; }
        public virtual DbSet<Reise> Reises { get; set; }
        public virtual DbSet<Reise_Hotel> Reise_Hotel { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<GUIUser> GUIUsers { get; set; }
    }
}
