//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui_Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBild
    {
        public long BildID { get; set; }
        public long HotelID { get; set; }
        public int Reihenfolge { get; set; }
        public byte[] Bild { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
